id: QmasnANNqFzyd14LdgXBMgBHZaTKuPHfJe4KS4ffczepGg
description: Adds a user to the database
tags: []
trigger:
    type: https
    method: GET
    paths:
        - /adduser
domains:
    - VigoCodingDomain
includes: 
    - /functions/adduser.go
execution:
    timeout: 60s
    memory: 10MB
    call: adduser
