id: QmZWVGa1KXrEnk2GAMM3TE9QWPJRS4jKHvwJQXsz8Zw9mU
description: Ping function test
tags: []
trigger:
    type: https
    method: POST
    paths:
        - /ping
domains:
    - VigoCodingDomain
includes:
    - /functions/addUser.go
execution:
    timeout: 60s
    memory: 1MB
    call: /ping
