id: QmfApspA7W4Zc3LE2CczYaPJAwTkNSDnpLciEJjmw3J2Eu
description: Get all files from a storage bucket
tags: 
    - getallfiles
trigger:
    type: https
    method: POST
    paths:
        - /getallfiles
domains:
    - VigoCodingDomain
includes: 
    - functions/getallfiles.go
execution:
    timeout: 60s
    memory: 10MB
    call: getallfiles
