id: QmQdakzBdamBpooezijY2nXPUH8ASHekWD8XKf1niGkBjY
description: Get user data by user UUID
tags: []
trigger:
    type: https
    method: POST
    paths:
        - /getuserbyid
domains:
    - VigoCodingDomain
includes:
    - /functions/getuserbyid.go
execution:
    timeout: 60s
    memory: 10MB
    call: getuserbyid
