id: QmacgzppxhbA5WxyESPFyeH6Bx6k76VHGVnTevbTrzw1AM
description: Ping example function
tags: []
trigger:
    type: https
    method: GET
    paths:
        - /readDataAsJson
domains:
    - VigoCodingDomain
includes:
    - /functions/ping.go
execution:
    timeout: 60s
    memory: 1MB
    call: readDataAsJson
