id: QmaWzeVDwadFwGFaM8emd99nw7NyTNYCQtq6UmEuRRBvdB
description: Read data from a database as json
tags:
    - rdfunc
trigger:
    type: https
    method: GET
    paths:
        - /rd
domains:
    - VigoCodingDomain
includes:
    - /functions/rd.go
execution:
    timeout: 120s
    memory: 5MB
    call: rd
