id: QmaWzeVDwadFwGFaM8emd99nw7NyTNYCQtq6UmEuRRBvdB
description: Read data from a database as json
tags: []
trigger:
    type: https
    method: GET
    paths:
        - /read
domains:
    - VigoCodingDomain
includes:
    - /functions/readDataAsJson.go
execution:
    timeout: 60s
    memory: 1MB
    call: readDataAsJson
