id: QmdJ2DB8eDPbs74SJZogwxnnnK2pcDuESdnkkqN4FrZW79
description: return some json to the user
tags: []
trigger:
    type: http
    method: GET
    paths:
        - /readjsonfromdb
domains:
    - VigoCodingDomain
includes:
    - /functions/readjson.go
execution:
    timeout: 60s
    memory: 10MB
    call: wok
