id: QmdNm1eMW2ytrDTxGnpfuocXbVSQgiquUXX7yf4Gru4NPj
description: TauList application endpoint
tags: []
trigger:
    type: https
    method: POST
    paths:
        - /taulistendpoint
domains:
    - GeneratedDomain
    - VigoCodingDomain
includes:
    - /functions/taulistendpoint.go
execution:
    timeout: 30s
    memory: 10MB
    call: taulistendpoint
