id: QmT9Lbw15qrXVx3nfunWh3hyNPzaFu3QZ88LCrJpPiBZgv
description: Uploads a file to storage teststorage
tags:
    - uploadfile
trigger:
    type: https
    method: POST
    paths:
        - /uploadfile
domains:
    - VigoCodingDomain
includes: 
    - functions/uploadfile.go
execution:
    timeout: 60s
    memory: 10MB
    call: uploadfile
